import { IBook } from './books';

export const BOOKS: IBook[] = [
  {
    position: 1,
    name: 'The Great Gatsby',
    description: 'A novel by American writer F. Scott Fitzgerald.',
    author: 'F. Scott Fitzgerald',
    rating: 4.3,
    bookWebsiteUrl: 'https://en.wikipedia.org/wiki/The_Great_Gatsby',
    numberOfPages: 180,
    printDate: new Date('April 10, 1925'),
    totalNumberOfBooks: 1000000,
  },
  {
    position: 2,
    name: 'To Kill a Mockingbird',
    description: 'A novel by Harper Lee.',
    author: 'Harper Lee',
    rating: 4.5,
    bookWebsiteUrl: 'https://en.wikipedia.org/wiki/To_Kill_a_Mockingbird',
    numberOfPages: 281,
    printDate: new Date('July 11, 1960'),
    totalNumberOfBooks: 750000,
  },
  {
    position: 3,
    name: '1984',
    description: 'A dystopian novel by George Orwell.',
    author: 'George Orwell',
    rating: 4.6,
    bookWebsiteUrl: 'https://en.wikipedia.org/wiki/Nineteen_Eighty-Four',
    numberOfPages: 328,
    printDate: new Date('June 8, 1949'),
    totalNumberOfBooks: 500000,
  },
  {
    position: 4,
    name: 'The Catcher in the Rye',
    description: 'A novel by J.D. Salinger.',
    author: 'J.D. Salinger',
    rating: 4.2,
    bookWebsiteUrl: 'https://en.wikipedia.org/wiki/The_Catcher_in_the_Rye',
    numberOfPages: 224,
    printDate: new Date('July 16, 1951'),
    totalNumberOfBooks: 900000,
  },
  {
    position: 5,
    name: 'Pride and Prejudice',
    description: 'A romantic novel by Jane Austen.',
    author: 'Jane Austen',
    rating: 4.4,
    bookWebsiteUrl: 'https://en.wikipedia.org/wiki/Pride_and_Prejudice',
    numberOfPages: 279,
    printDate: new Date('January 28, 1813'),
    totalNumberOfBooks: 1200000,
  },
];
